[package]
# changeme
name = "enum-util"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["enum-util-attr", "enum-util-core"]

[dependencies]
enum-util-attr = { version = "0.1.0", path = "enum-util-attr" }
