[package]
name = "attribute-macro-template-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
attribute-macro-template-core = { version = "0.1.0", path = "../attribute-macro-template-core" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"

