[package]
name = "enum-util-attr"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
enum-util-core = { version = "0.1.0", path = "../enum-util-core" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"

